[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

# SPA redirect rule - critical for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# WWW redirect (keep existing)
[[redirects]]
  from = "https://www.edueasy.co.za/*"
  to = "https://edueasy.co.za/:splat"
  status = 301
  force = true

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://plausible.io https://cdn.gpteng.co; connect-src 'self' https://pensvamtfjtpsaoeflbx.supabase.co https://pensvamtfjtpsaoeflbx.functions.supabase.co https://www.google-analytics.com https://plausible.io; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
