name: ci
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm tsc --noEmit
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Banned lucide-react imports in pages
        run: |
          ! grep -R "from 'lucide-react'" src/pages || (echo "lucide-react import found in pages"; exit 1)
      - name: Banned step status strings (outside types/ui.ts)
        run: |
          ! grep -R --exclude=src/types/ui.ts -E "'(completed|current|upcoming)'" src || (echo "banned status found"; exit 1)